name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of teh deployable artifact files
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name}}
      - name: List Files
        run: ls
      - name: Output Information
        run: echo 'Deploying & uploading...'
