name: Use Reuse
on:
  push:
    branches:
      - master
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md
  reuse:
    needs: build_and_test
    uses: ./.github/workflows/reusable.yml
    with:
      artifact-name: dist-without-markdown
    #secrets:
    # some-secret: "${{ secrets.some-secret}}"
  print-deploy-result:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Print deploy output
        run: echo "${{ needs.build_and_test.outputs.result}}"
